name: CI Pipeline

permissions:
  contents: read

on:
  push:
    branches: ['main']

jobs:
  supabase-db-push:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm ci
      # Version 1.6.0
      - uses: supabase/setup-cli@b60b5899c73b63a2d2d651b1e90db8d4c9392f51
      - name: Link to Supabase project
        run: |
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          echo "Linked Supabase project ${{ secrets.SUPABASE_PROJECT_REF }}"
      - name: Push Supabase schema and seeds
        run: |
          supabase db push --include-all
          echo "Supabase schema and seeds pushed"

  build:
    needs: [supabase-db-push]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
